const { SlashCommandBuilder } = require('discord.js');

module.exports = {
  data: new SlashCommandBuilder()
    .setName('delete')
    .setDescription('Delete')
    .addSubcommand((subcommand) => subcommand
      .setName('shuffleroles')
      .setDescription('Deletes the roles generated by the shufflers')
    )
  ,
  run: async ({ interaction }) => {
    
  }
}